name: reusable-callee
'on':
  workflow_call:
    inputs:
      message:
        required: true
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.message }}"
