name: cache
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: cache
        uses: actions/cache@v4
        with:
          key: my-cache-${{ github.sha }}
          path: .cache/

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .cache
          echo "expensive computation" > .cache/result.txt

      - run: cat .cache/result.txt
