name: expressions
'on': push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GREETING: hello
    steps:
      - name: String functions
        run: |
          echo "contains: ${{ contains('hello world', 'world') }}"
          echo "startsWith: ${{ startsWith('hello', 'hel') }}"
          echo "endsWith: ${{ endsWith('hello', 'llo') }}"
      - name: JSON functions
        run: |
          echo "toJSON: ${{ toJSON(env) }}"
      - name: Env expression
        run: echo "greeting is ${{ env.GREETING }}"
